# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432 #5432 portunu disari actik
    environment:
      POSTGRES_PASSWORD: benimSifrem

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#docker-compose -f docker-compose.yml up -d
#docker login --username your_user_name